# Generated by Django 2.1 on 2018-10-15 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_payments', '0002_auto_20180927_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencygateway',
            name='gateway',
            field=models.CharField(choices=[('coinpayments', 'CoinPayments'), ('bitcoin', 'Bitcoin'), ('bitcoinz', 'Bitcoin Z'), ('bitgo', 'BitGo'), ('bepay', 'BePay')], max_length=50, verbose_name='Gateway'),
        ),
    ]
