# Generated by Django 2.0.1 on 2018-01-20 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_payments', '0002_auto_20180119_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybanks',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
    ]
