# Generated by Django 2.0.1 on 2018-01-25 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_payments', '0005_auto_20180125_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencygateway',
            name='currency',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gateway', to='exchange_core.Currencies'),
        ),
    ]
