# Generated by Django 2.0.1 on 2018-03-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_payments', '0008_auto_20180301_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencygateway',
            name='gateway',
            field=models.CharField(choices=[('coinpayments', 'CoinPayments'), ('tcoin', 'Tcoin'), ('bitgo', 'BitGo')], max_length=50),
        ),
    ]
