# Generated by Django 2.0.1 on 2018-04-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_payments', '0015_auto_20180401_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='provider',
            field=models.CharField(choices=[('coinpayments', 'coinpayments'), ('tcoin', 'tcoin'), ('bitcoin', 'bitcoin'), ('bitcoinz', 'bitcoinz'), ('bitgo', 'bitgo'), ('advcash', 'advcash')], max_length=20, verbose_name='Provider'),
        ),
        migrations.AlterField(
            model_name='currencygateway',
            name='gateway',
            field=models.CharField(choices=[('coinpayments', 'CoinPayments'), ('tcoin', 'Tcoin'), ('bitcoin', 'Bitcoin'), ('bitcoinz', 'Bitcoin Z'), ('bitgo', 'BitGo'), ('advcash', 'Advcash')], max_length=50, verbose_name='Gateway'),
        ),
    ]
