# Generated by Django 2.1.1 on 2018-09-17 20:12

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_core', '0008_auto_20180917_2004'),
        ('exchange_payments', '0016_auto_20180425_1817'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='credentials',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='credentials',
            name='user',
        ),
        migrations.AddField(
            model_name='companybanks',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_banks', to='exchange_core.Currencies', verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='bankdeposits',
            name='amount',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='currencygateway',
            name='gateway',
            field=models.CharField(choices=[('coinpayments', 'CoinPayments'), ('tcoin', 'Tcoin'), ('bitcoin', 'Bitcoin'), ('bitcoinz', 'Bitcoin Z'), ('bitgo', 'BitGo')], max_length=50, verbose_name='Gateway'),
        ),
        migrations.DeleteModel(
            name='Credentials',
        ),
    ]
